/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym;

import javax.swing.table.DefaultTableModel;

    void setVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void updateRateDefault() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void updateFeePreview() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void clearForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void handleDelete() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void handleUpdate() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void handleSave() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

/**
 *
 * @author IZZATUL NAZIFA
 */
public class GymMembershipForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GymMembershipForm.class.getName());

    /**
     * Creates new form GymMembershipForm
     */
    private int selectedMemberID = -1;
    private javax.swing.table.DefaultTableModel tableModel;
    
    public GymMembershipForm() {
        initComponents();
        setupTable();
        updateRateDefault();
        loadTableData();
}

        private void loadTableData() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private void updateRateDefault() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblFee = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        table = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Member Name:");

        jLabel2.setText("IC Number:");

        txtIC.addActionListener(this::txtICActionPerformed);

        jLabel3.setText("MembershipType:");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Yearly" }));
        cmbType.addActionListener(this::cmbTypeActionPerformed);

        jLabel4.setText("Fee/Rate (RM):");

        txtRate.setText("80.00");
        txtRate.addActionListener(this::txtRateActionPerformed);

        jLabel5.setText("Calculated Fee:");

        lblFee.setText("RM 0.00");

        jLabel6.setText("Start Date (yyyy-mm-dd):");

        txtStartDate.addActionListener(this::txtStartDateActionPerformed);

        jLabel7.setText("Yearly Discount(%):");

        txtDiscount.setText("15");
        txtDiscount.addActionListener(this::txtDiscountActionPerformed);

        btnSave.setBackground(new java.awt.Color(204, 255, 204));
        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnUpdate.setBackground(new java.awt.Color(204, 255, 204));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setBackground(new java.awt.Color(204, 255, 204));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setBackground(new java.awt.Color(204, 255, 204));
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "IC Number", "Type", "Start Date", "Rate (RM)", "Discount (%)", "Fee (RM)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSave)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblFee, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(cmbType, 0, 140, Short.MAX_VALUE)
                                    .addComponent(txtRate))))
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(36, 36, 36)
                        .addComponent(btnDelete)
                        .addGap(29, 29, 29)
                        .addComponent(btnClear)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFee)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addGap(8, 8, 8)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateActionPerformed

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void txtICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtICActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
     handleSave();    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
     handleUpdate();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        handleDelete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        updateRateDefault();
        updateFeePreview();
    }//GEN-LAST:event_cmbTypeActionPerformed

// ---------- Setup table columns and row-click listener ----------
    private void setupTable() {
        String[] columns = {"ID", "Name", "IC Number", "Type", "Start Date", "Rate (RM)", "Discount (%)", "Fee (RM)"};
        DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
         table.setModel(tableModel);

    // Hide the ID column visually - staff sees Name first, but the
    // system still tracks the ID internally for Update/Delete operations.
          table.getColumnModel().getColumn(0).setMinWidth(0);
          table.getColumnModel().getColumn(0).setMaxWidth(0);
          table.getColumnModel().getColumn(0).setWidth(0);

          table.getSelectionModel().addListSelectionListener(e -> {
        // baris lain kekal sama, tak berubah
        
// ---------- Load all records from database into the JTable ----------
private void loadTableData() {
    tableModel.setRowCount(0);
    java.util.List<Membership> memberships = DatabaseHelper.getAllMemberships();

    for (Membership m : memberships) {
        tableModel.addRow(new Object[]{
            m.getMemberID(),
            m.getMemberName(),
            m.getIcNumber(),
            m.getMembershipType(),
            m.getStartDate(),
            String.format("%.2f", m.getRate()),
            String.format("%.2f", m.getDiscountPercent()),
            String.format("%.2f", m.calculateFee())
        });
    }
}

// ---------- Validate form input ----------
private String validateInput() {
    String name = txtName.getText().trim();
    String ic = txtIC.getText().trim();
    String startDate = txtStartDate.getText().trim();
    String rateText = txtRate.getText().trim();

    if (name.isEmpty() || ic.isEmpty() || startDate.isEmpty() || rateText.isEmpty()) {
        return "All fields must be filled in.";
    }
    if (!startDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
        return "Start Date must be in yyyy-MM-dd format (e.g., 2026-09-13).";
    }
    try {
        double rate = Double.parseDouble(rateText);
        if (rate <= 0) {
            return "Fee/rate must be a positive number.";
        }
    } catch (NumberFormatException e) {
        return "Fee/rate must be a valid number.";
    }
    if ("Yearly".equals(cmbType.getSelectedItem())) {
        try {
            double discount = Double.parseDouble(txtDiscount.getText().trim());
            if (discount < 0 || discount > 100) {
                return "Discount must be between 0 and 100.";
            }
        } catch (NumberFormatException e) {
            return "Discount must be a valid number.";
        }
    }
    return null;
}

// ---------- Build the correct Membership subclass from form input (polymorphism) ----------
private Membership buildMembershipFromForm() {
    String name = txtName.getText().trim();
    String ic = txtIC.getText().trim();
    String startDate = txtStartDate.getText().trim();
    String type = (String) cmbType.getSelectedItem();
    double rate = Double.parseDouble(txtRate.getText().trim());

    Membership membership;
    if (type.equals("Yearly")) {
        double discount = Double.parseDouble(txtDiscount.getText().trim());
        membership = new YearlyMembership(name, ic, startDate, rate, discount);
    } else {
        membership = new MonthlyMembership(name, ic, startDate, rate);
    }
    return membership;
}

// ---------- Clear the form ----------
private void clearForm() {
    txtName.setText("");
    txtIC.setText("");
    cmbType.setSelectedIndex(0);
    txtStartDate.setText("");
    updateRateDefault();
    lblFee.setText("RM0.00");
    selectedMemberID = -1;
    table.clearSelection();
}

// ---------- Save / Update / Delete handlers ----------
private void handleSave() {
    String error = validateInput();
    if (error != null) {
        javax.swing.JOptionPane.showMessageDialog(this, error, "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    Membership membership = buildMembershipFromForm();
    lblFee.setText("RM" + String.format("%.2f", membership.calculateFee()));

    boolean success = DatabaseHelper.addMembership(membership);
    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Member saved successfully.");
        loadTableData();
        clearForm();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to save member.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

private void handleUpdate() {
    if (selectedMemberID == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a member from the table first.",
                "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String error = validateInput();
    if (error != null) {
        javax.swing.JOptionPane.showMessageDialog(this, error, "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    Membership membership = buildMembershipFromForm();
    membership.setMemberID(selectedMemberID);

    boolean success = DatabaseHelper.updateMembership(membership);
    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Member updated successfully.");
        loadTableData();
        clearForm();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to update member.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

private void handleDelete() {
    if (selectedMemberID == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a member from the table first.",
                "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this member?",
            "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        boolean success = DatabaseHelper.deleteMembership(selectedMemberID);
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Member deleted successfully.");
            loadTableData();
            clearForm();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to delete member.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblFee;
    private javax.swing.JScrollPane table;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}
